
typedef struct _ksuse {
    int sid;
    void *addy;
    unsigned long longAddy;
    unsigned short seq;
    unsigned short pseq;
    char *unm;
    unsigned int pid;
    char *opc;
    short opcnum;
    int ksledClassid;
    char *ksledClassName;
    char* oct;
    char *octName;
    char *lna;
    char *pnm;
    char *opcP1;
    long long p1;
    char *opcP2;
    long long p2;
    char *opcP3;
    long long p3;
    char *latch;
    long long sql;
    unsigned int sqh;
    long long psq;
    unsigned int pha;
    int fil;
    long long blk;
    unsigned short slt;
    unsigned short obj;
    int idl;
    int flg;
    int lui;
    char* state;
    char* con;
} Ksuse;

void initKsuse(Ksuse* ksuse);